"""value to amount

Revision ID: d1d06a384d7b
Revises: 5ac21de4dc51
Create Date: 2022-03-05 21:57:39.899979

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd1d06a384d7b'
down_revision = '5ac21de4dc51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('amount', sa.Numeric(), nullable=False))
    op.drop_column('transaction', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('value', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('transaction', 'amount')
    # ### end Alembic commands ###
